function factorScoresmyParticipants = importfileSEM(filename, dataLines)
%IMPORTFILE Import data from a text file
%  FACTORSCORESMYPARTICIPANTS = IMPORTFILE(FILENAME) reads data from
%  text file FILENAME for the default selection.  Returns the numeric
%  data.
%
%  FACTORSCORESMYPARTICIPANTS = IMPORTFILE(FILE, DATALINES) reads data
%  for the specified row interval(s) of text file FILENAME. Specify
%  DATALINES as a positive scalar integer or a N-by-2 array of positive
%  scalar integers for dis-contiguous row intervals.
%
%  Example:
%  factorScoresmyParticipants = importfile("G:\My Drive\Science\Manuscripts\0000_Virtue-Griffiths_Aperiodic activity working memory\figures\factorScores_myParticipants.csv", [3, Inf]);
%
%  See also READTABLE.
%
% Auto-generated by MATLAB on 22-Jun-2021 15:23:22

%% Input handling

% If dataLines is not specified, define defaults
if nargin < 2
    dataLines = [3, Inf];
end

%% Setup the Import Options
opts = delimitedTextImportOptions("NumVariables", 9);

% Specify range and delimiter
opts.DataLines = dataLines;
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["ID", "Ospan", "SSSpan", "BDS", "nBack", "ComplexSpanFactorScoreEstimate", "VarName7", "VarName8", "VarName9"];
opts.VariableTypes = ["double", "double", "double", "double", "double", "double", "double", "double", "double"];
opts = setvaropts(opts, [7, 8, 9], "TrimNonNumeric", true);
opts = setvaropts(opts, [7, 8, 9], "ThousandsSeparator", ",");
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
factorScoresmyParticipants = readtable(filename, opts);

%% Convert to output type
factorScoresmyParticipants = table2array(factorScoresmyParticipants);
end